### ISSUE TITLE
Use a sensible license

### ISSUE THREAD

**Issue by joebandenburg** [ronmamo/reflections#119]
Wikipedia says:
> The license was approved as a GPL-compatible free software license by the Free Software Foundation but its use is “not recommended.”

Please relicense your code under a better open source license. Alternatively, you could put the code in the public domain.

**Comment by ronmamo** [comment]
reconsider sensible.

**Comment by wojtek-kalicinski** [comment]
I know you closed this, but I'd like to add arguments to why I think this request makes sense and I would like to +1 it.

While the WTFPL license would be perfectly fine for some jurisdictions, it is very much akin to "public domain" which in many countries simply does not exist or is not a valid contract. 

The vague wording and lack of warranty disclaimer unfortunately make it explicitly forbidden to use WTFPL-licensed software in many corporate environments. If you want your work to be truly universally available for reuse please, please reconsider using one of the OSI-approved, permissive, copyfree licences like BSD, MIT, Apache 2.0 or even CC BY.
 
I'd love to use your lib, but unfortunately cannot due to WTFPL :(
