### ISSUE TITLE
pom.xml id=latest poitns to old guava 15

### ISSUE THREAD

**Issue by dcaillia** [ronmamo/reflections#132]
```
    <profile>
        <id>latest</id>
        <properties>
            <guava.version>15.0</guava.version>
            <javassist.version>3.19.0-GA</javassist.version>
```

I guess that should be at least guava 18.0.

**Comment by Pitority** [comment]
Upvote this issue. I just removed this because of this old dependency... 
I tried to exclude this dependency and add the newest one manually -> java.lang.ClassNotFoundException: com.google.common.base.Predicate

**Comment by freddyb2** [comment]
I guess the best could be the last one, i.e.
<guava.version>19.0</guava.version>

**Comment by Pitority** [comment]
Yes but I am pretty sure this wont compile since they removed/move/renamed at least the class i mentioned above between 15 and 19. So changing the pom is not enough

**Comment by jshook** [comment]
This issue is conflicting with other software that relies on guava. The other artifact actively checks for the old guava bugs and refuses to load the affected version. Please update to a recent version. Even gauva 16 might be an improvement. guava 19 would be even better if you can sort out the Predicate dependency.

**Comment by morvael** [comment]
I have cloned the repository, updated POM to use latest version of every library, and the code works.
