### ISSUE TITLE
NPE if classpath element directory is not created

### ISSUE THREAD

**Issue by jonnyzzz** [ronmamo/reflections#155]
[main] WARN org.reflections.Reflections - could not create Dir using directory from url file:/Users/jonnyzzz/Work/vcs-hosting/src/grpc-protobuf-codegen/build/resources/main. skipping.
java.lang.NullPointerException
	at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:239)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:98)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at org.reflections.Reflections.scan(Reflections.java:237)
	at org.reflections.Reflections.scan(Reflections.java:204)
	at org.reflections.Reflections.<init>(Reflections.java:129)
	at org.reflections.Reflections.<init>(Reflections.java:170)

I use gradle generated classpath. By default it includes a number of entitied that does not exist. It's Ok for JVM, but makes org reflections spamming errors to logs

**Comment by hendrikebbers** [comment]
We are having the same problem. I would love to have an interface to handle such exceptions. Example:
```

ClasspathScanExceptionHandler {

     onScanError(ClasspathScanException e) throws CriticalClasspathScanException;

}

Reflections.setExceptionHandler(ClasspathScanExceptionHandler e);

```
Instead of printing the error the exception handler will be called. If this do not throw a critical exception the scan continues. Otherwise the scan will stop / fail and the `Reflections.scan` method throws a runtime exception.

I would love to provide a PR for this if you think that this is a good solution.

About the gradle problem: We only have this on some setups and I think that it is related to gradle / intelliJ since on some setups an empty "main" folder will be created a application start (by gradle or intelliJ) and on other system the "main" folder will not be created :( So the only think how this can be solved by reflections is a better exception handling.

**Comment by ronmamo** [comment]
Manually merged. Thanks!
