### ISSUE TITLE
SubtypeScanner 

### ISSUE THREAD

**Issue by poseidon42** [ronmamo/reflections#71]
First, great Tool.
But finding this bug after refactoring took some time... ;-D

I have a package "a.b.c" and one "a.b.c.impl".
In the first package, I have an (abstract class) "_X_" and another abstract class "_Y_" extending X.
In the second package, I have classes Z extending Y, so Z instanceof X is true.

So far, now comes the fun: I need to have the classes inside the second package, not the abstract ones. Intuition (and docs) say, this is the way to go:
`final Reflections r = new Reflections("a.b.c.impl");`
`Set... = r.getSubTypesOf(X.class);`

But the set is empty - too bad.

This one works, but I have to filter the abstract classes...? strange.

`final Reflections r = new Reflections("a.b.c");` (without ".impl")
`Set... = r.getSubTypesOf(X.class);`

or maybe i missed s.th.?

**Comment by math-th** [comment]
Hello,
I also have the same problem with interface.
If I have a interface **MyInterface**, and a abstract class **MyInterfaceBaseImpl**, if I scan a package to find all subtypes of **MyInterface**, the types will not be found if the class **MyInterfaceBaseImpl** is not scanned.

**So the workarround is** : scan to a higher package and apply a post filter to your target package once the subtypes are found.

**Comment by subwiz** [comment]
Would be great if we have whole inheritance-tree scanning.

**Comment by draenor** [comment]
Further, if I scan for implementations of `Foo` and `Foo` itself is not scanned it will not work. 

This is bad because `Foo` might be located in `bigpackage` while sought implementation reside in `bigpackage.smallpackage`.

**Comment by ronmamo** [comment]
It is documented (although might not be very intuitive), that all relevant
package roots should be scanned, otherwise there is no transitivity.
However, adding too many packages increases scan time, and in some cased
not all packages are known a priori.

Still, another approach is to expand the store after scanning time, see
https://github.com/ronmamo/dropwizard-bundler/blob/master/bundler/src/main/java/dev/dropwizard/bundler/util/ReflectionsHelper.java

For your case:
ReflectionsHelper.expandSupertypes(reflections, SubTypesScanner.class, new
String[][]{"bigpackage});

HTH

On Dec 15, 2015 8:53 AM, "Johan Sjöberg" <notifications@github.com> wrote:
>
> Further, if I scan for implementations of Foo and Foo itself is not
scanned it will not work.
>
> This is bad because Foo might be located in bigpackage while sought
implementation reside in bigpackage.smallpackage.

**Comment by marvec** [comment]
In our project, I fixed that by implementing TransitiveInterfaceScanner (a subclass here https://github.com/px3/SilverWare/blob/devel/microservices/src/main/java/io/silverware/microservices/util/DeploymentScanner.java). The difficult part is that getSubTypesOf(clazz) does not use this scanner so I had to workaround this (see method lookupSubtypes(clazz) in my DeploymentScanner). What do you think about incorporating this scanner or functionality into Reflections?

**Comment by jevgeniv** [comment]
@ronmamo:
> It is documented (although might not be very intuitive), that all relevant
> package roots should be scanned, otherwise there is no transitivity.

I guess this restriction is there for the sake of performance?

My case differs a little from OP, and in my opinion the outcome is at least surprising. Let's say I have:
- ```class a.b.Model```
- ```class a.Bar extends a.b.Model```
- ```class a.b.Foo extends a.Bar```

Meaning that `a.b.Foo` is a sub-type of `a.b.Model`. However I will not get a match for `a.b.Foo` when scanning within package `a.b`: `new Reflections("a.b").getSubTypesOf(Model.class)`

Just asking to consider this case and share your opinion on whether it should be supported out-of-the-box.

**Comment by Ramblurr** [comment]
My case is quite simple:

I want to get all classes in a package that extend `Exception.class`, I thought this would be as easy as:
```java
Reflections reflections = new Reflections("my.package.foo");
Set<Class<? extends Exception>> throwableTypes = reflections.getSubTypesOf(Exception.class);
```

But this in fact doesn't work because "my.package.foo" doesn't include the `Exception.class`, so it returns an empty set.

Next I tried customizing the SubTypesScanner:

1. include `java.lang` to pickup Exception.class
2. Include my package
3. Configure the SubTypesScanner to  only include results from my pacakge

```java
        Reflections reflections = new Reflections(new ConfigurationBuilder()
                .setUrls(ClasspathHelper.forClassLoader())
                .filterInputsBy(new FilterBuilder()
                        .include("java.lang\\..*")
                        .includePackage("my.package.foo"))
                .setScanners(
                       new SubTypesScanner()
                           .filterResultsBy(new FilterBuilder().includePackage("my.package.foo")));
        Set<Class<? extends Exception>> throwableTypes = reflections.getSubTypesOf(Exception.class);
```

**Result**: This also returns an empty Set!!

In the end my solution was to use the default SubTypesScanner without results filter, then iterate over the set manually to remove all the `java.lang` exceptions.

```
        Iterator<Class<? extends Exception>> iterator = throwableTypes.iterator();
        while (iterator.hasNext())
        {
            if (!iterator.next().getPackage().getName().startsWith("my.package.foo"))
                iterator.remove();
        }
```

Is this a bug in the library? Or am I just not understanding how it is supposed to be used?
